### ISSUE TITLE
Build for DigiRiteLogger.cs fails on references to WriteLogClrTypes

### ISSUE THREAD

**Issue by K6TD** [w5xd/Digi-Rite#5]
`The type or namespace name 'WriteLogClrTypes' could not be found (are you missing a using directive or an assembly reference?) | DigiRiteLogger | C:\Users\kevin\Source\Repos\Digi-Rite2\DigiRiteLogger\WriteLog.cs | 16`

On branch BETA.

The commit comment say 

> factor out WriteLogClrTypes

**Comment by w5xd** [comment]
fixed by c1e7189847218eab1bb9f65394efeaf1c66e977c
